### ISSUE TITLE
Current step star position

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/reviewhunt-web#14]
![image](https://user-images.githubusercontent.com/1332279/61772627-b120f800-ae2d-11e9-833b-e8d3b9d66ae2.png)

The star should be on the top of the icon 

![image](https://user-images.githubusercontent.com/1332279/61772663-c5fd8b80-ae2d-11e9-9acb-c5c71f659332.png)

**Comment by ggomaeng** [comment]
After discussion with @cyh76507707, we made it go over the reward because the star overlapped with the vertical line on mobile devices. However, I think the solution below is better for mobile devices (star next to the reward on mobile).
 
![image](https://user-images.githubusercontent.com/18402191/61807829-409dc980-ae75-11e9-9b0c-66b420d48b06.png)
