### ISSUE TITLE
Add Device Restriction

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/reviewhunt-web#144]
Let's add the device restriction check box on the campaign creation page as below:
(Zeplin: `Create Campaign - 1`)

![Screenshot 2019-07-29 17 42 28](https://user-images.githubusercontent.com/15100667/62066121-6259d080-b228-11e9-853e-1dd27e29cac6.png)

When the campaign has only iPhone or Android restriction, we can add an alert message when to click to join the campaign like this:

```This campaign is only for Android user. Are you using an Android phone?```
Yes, No

**Comment by ggomaeng** [comment]
@sydneyitguy can you add the necessary API for this?

**Comment by sydneyitguy** [comment]
In BUZZi's case, makers would check 
Android and Web App => because they have both.

Then we would display
"This campaign is for Android or Web user. Are you using an Android phone or Web browser?"
However, the hunters must have Android phone to proceed the quest.

It's probably just confusing for both side.
Let's just leave it as it is now, and let's just add a general message like

"Please read the instruction carefully and make sure you have required devices to proceed this quest."

**Comment by cyh76507707** [comment]
Change the modal alert message when the hunter join the quest as below:

**Please note**
[v] You MUST submit the quest you join. If not, you will get penalty point that may limit your Reviewhunt activities. After you join, you must submit this quest in 24 hours.
[  ] This campaign is only for Android user. Are you using an Android phone?

OK button should be only active when both are checked.

**Comment by ggomaeng** [comment]
Closing because we've discussed and finalized on adding a modal with two checkboxes.
