### ISSUE TITLE
[SUGGESTION] Add Refresh/Reset Button for Bounty so Far

### ISSUE THREAD

**Issue by Chuuuckie** [Steemhunt/reviewhunt-web#251]
There should be an option to reset the value of the total bounty so far, as a User I dont really get what is the purpose of this since there is already a wallet for that.

![image](https://user-images.githubusercontent.com/36227271/63279374-73ec4080-c2db-11e9-92e2-adaa598c4b63.png)

**Comment by sydneyitguy** [comment]
@Chuuuckie 

You cannot see total accumulated reward you earned on Reviewhunt on your wallet directly because transactions are mixed with Steemhunt and you can also withdraw the balance to exchanges.

That value is meant to be a total accumulated reward regardless of withdrawals, thus we don't h ave reset option there.
